#line 1 "src/core/flex_qgsexpressionlexer.cpp"

#line 3 "src/core/flex_qgsexpressionlexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define exp__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer exp__create_buffer
#endif

#ifdef yy_delete_buffer
#define exp__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer exp__delete_buffer
#endif

#ifdef yy_scan_buffer
#define exp__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer exp__scan_buffer
#endif

#ifdef yy_scan_string
#define exp__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string exp__scan_string
#endif

#ifdef yy_scan_bytes
#define exp__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes exp__scan_bytes
#endif

#ifdef yy_init_buffer
#define exp__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer exp__init_buffer
#endif

#ifdef yy_flush_buffer
#define exp__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer exp__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define exp__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state exp__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define exp__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer exp__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define exp_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state exp_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define exp_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state exp_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define exp_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack exp_ensure_buffer_stack
#endif

#ifdef yylex
#define exp_lex_ALREADY_DEFINED
#else
#define yylex exp_lex
#endif

#ifdef yyrestart
#define exp_restart_ALREADY_DEFINED
#else
#define yyrestart exp_restart
#endif

#ifdef yylex_init
#define exp_lex_init_ALREADY_DEFINED
#else
#define yylex_init exp_lex_init
#endif

#ifdef yylex_init_extra
#define exp_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra exp_lex_init_extra
#endif

#ifdef yylex_destroy
#define exp_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy exp_lex_destroy
#endif

#ifdef yyget_debug
#define exp_get_debug_ALREADY_DEFINED
#else
#define yyget_debug exp_get_debug
#endif

#ifdef yyset_debug
#define exp_set_debug_ALREADY_DEFINED
#else
#define yyset_debug exp_set_debug
#endif

#ifdef yyget_extra
#define exp_get_extra_ALREADY_DEFINED
#else
#define yyget_extra exp_get_extra
#endif

#ifdef yyset_extra
#define exp_set_extra_ALREADY_DEFINED
#else
#define yyset_extra exp_set_extra
#endif

#ifdef yyget_in
#define exp_get_in_ALREADY_DEFINED
#else
#define yyget_in exp_get_in
#endif

#ifdef yyset_in
#define exp_set_in_ALREADY_DEFINED
#else
#define yyset_in exp_set_in
#endif

#ifdef yyget_out
#define exp_get_out_ALREADY_DEFINED
#else
#define yyget_out exp_get_out
#endif

#ifdef yyset_out
#define exp_set_out_ALREADY_DEFINED
#else
#define yyset_out exp_set_out
#endif

#ifdef yyget_leng
#define exp_get_leng_ALREADY_DEFINED
#else
#define yyget_leng exp_get_leng
#endif

#ifdef yyget_text
#define exp_get_text_ALREADY_DEFINED
#else
#define yyget_text exp_get_text
#endif

#ifdef yyget_lineno
#define exp_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno exp_get_lineno
#endif

#ifdef yyset_lineno
#define exp_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno exp_set_lineno
#endif

#ifdef yyget_column
#define exp_get_column_ALREADY_DEFINED
#else
#define yyget_column exp_get_column
#endif

#ifdef yyset_column
#define exp_set_column_ALREADY_DEFINED
#else
#define yyset_column exp_set_column
#endif

#ifdef yywrap
#define exp_wrap_ALREADY_DEFINED
#else
#define yywrap exp_wrap
#endif

#ifdef yyget_lval
#define exp_get_lval_ALREADY_DEFINED
#else
#define yyget_lval exp_get_lval
#endif

#ifdef yyset_lval
#define exp_set_lval_ALREADY_DEFINED
#else
#define yyset_lval exp_set_lval
#endif

#ifdef yyget_lloc
#define exp_get_lloc_ALREADY_DEFINED
#else
#define yyget_lloc exp_get_lloc
#endif

#ifdef yyset_lloc
#define exp_set_lloc_ALREADY_DEFINED
#else
#define yyset_lloc exp_set_lloc
#endif

#ifdef yyalloc
#define exp_alloc_ALREADY_DEFINED
#else
#define yyalloc exp_alloc
#endif

#ifdef yyrealloc
#define exp_realloc_ALREADY_DEFINED
#else
#define yyrealloc exp_realloc
#endif

#ifdef yyfree
#define exp_free_ALREADY_DEFINED
#else
#define yyfree exp_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define exp_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[272] =
    {   0,
        0,    0,    0,    0,   55,   53,   51,   51,   53,   53,
       53,   29,   53,   39,   26,   24,   40,   25,   53,   28,
       42,   14,    9,   15,   53,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   30,   53,   16,
        3,    3,    5,    3,    3,    3,    3,    3,    3,    4,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,   51,   10,    0,   50,   47,
       47,    0,   44,    0,   52,   41,    1,   27,    0,   42,
        0,   11,   13,   12,   48,    0,   49,    0,   49,   49,

       49,    0,   41,   49,   49,   49,   49,   31,   21,   49,
       49,   49,    8,   49,   49,   49,   23,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
       47,   47,   47,   52,   52,    0,   41,   48,   46,    7,
       49,   49,   49,   38,   49,   49,    0,   49,    6,   49,
       49,   49,   49,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,   45,    0,   41,   46,
       49,   34,   37,   49,   49,    0,   17,    0,   33,   36,
       43,   35,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   49,   43,
       19,    0,    0,    0,    3,    3,    3,    3,    3,    3,
       49,   22,    0,    0,    3,    3,    3,    3,   32,    0,
        0,    3,    3,    3,    0,   18,    3,    3,   20,    3,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    1,    9,   10,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,    1,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   29,   32,   33,   29,   34,   35,   29,
       29,   36,   37,   38,   39,   29,   40,   41,   41,   29,
       10,   42,   10,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   29,   51,   52,   29,   53,   54,   29,   55,
       56,   29,   29,   57,   58,   59,   60,   29,   61,   41,
       41,   29,    1,   62,    1,   63,    1,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,

       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    2,    1,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    6
    } ;

static const flex_int16_t yy_base[286] =
    {   0,
        0,    0,   64,    0,  712, 1286,  127,  130,  686,  697,
      661, 1286,  126, 1286, 1286, 1286, 1286,  661,  653,  125,
      122,  122, 1286,  645,    0,  142,  151,  154,  148,  199,
      161,  171,  178,  189,  216,  233,  237, 1286,  600, 1286,
        0,  171,  219,  638,  156,  290,    0,  235,    0,  634,
        0,    0,  632,  625,  623,  233,  127,    0,  591,  354,
      418,  230,  238,  106,  471,  461,  453,  234,  457,  463,
      464,  459,    0,  523,    0,  272, 1286,  578,  572,    0,
      236,  185,  568,  567,  183,  505, 1286, 1286,  548,  512,
      198, 1286, 1286, 1286,    0,  531,  534,  531,  538,  541,

      544,  511,  565,  569,  572,  589,  592,  601,  610,  613,
      622,  630,  633,  650,  653,  670, 1286,    0,  499,    0,
      547,  423,  719,  782,  638,  356,  187, 1286,  267,  572,
        0,  340,  652,  543,    0,    0,    0,  845,  687,  232,
      281,  652,  649,  627,  245,  546,  659,  696,  575,  711,
      475,  744,  718,  715,  661,  563,  709,  720,  779,    0,
        0,  600,  543,  239, 1286,  743,  241,    0,  707,  805,
      838,  866,  871,  812,  877,  898,  888,  901,  815,  907,
      929,  942,  934,  787,  911,  212,  520,    0,  755,  230,
      991,  818,  722,  887,  930,  931,  828,  980,  984, 1018,

      932,  974,  863,  907,  992,  919,    0,  214,  197,  833,
     1028, 1040, 1046, 1057, 1063,  919, 1067, 1076, 1084, 1093,
     1096, 1101,  979,  178,  172,  969, 1074,  933,  960, 1083,
     1086, 1016, 1028, 1122, 1034, 1081, 1082, 1084, 1140, 1143,
     1146, 1093, 1100, 1120, 1129, 1125, 1126, 1124, 1132, 1135,
     1167, 1286, 1142, 1143, 1143,    0, 1148, 1150, 1188, 1156,
      649, 1159, 1163,  845, 1170, 1286, 1172,    0, 1286,    0,
     1286, 1222,  164, 1228,  132, 1233, 1239, 1245, 1251, 1253,
     1259, 1261, 1267, 1273, 1279
    } ;

static const flex_int16_t yy_def[286] =
    {   0,
      271,    1,  271,    3,  271,  271,  271,  271,  271,  272,
      273,  271,  274,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  275,  276,  276,  276,  276,  276,
      276,   30,  276,  276,  276,  276,  276,  271,  271,  271,
      277,  277,  271,  277,  278,  271,  277,  279,  277,  271,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  271,
      271,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  277,  277,  277,  271,  271,  272,  271,  280,
      280,  274,  271,  274,  281,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  282,  271,  276,  271,  276,  276,

      276,  271,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  271,  277,  277,  277,
      278,  277,  283,  283,  279,  277,  279,  271,  284,  277,
      277,  277,  277,  277,  277,  277,  277,  285,  277,   61,
      277,   61,   61,   61,  277,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  277,
      280,  280,  280,  281,  271,  271,  271,  282,  271,  276,
      276,  276,  276,  276,  276,  276,  271,  276,  276,  276,
      276,  276,  276,  124,  124,  124,  284,  277,  277,  277,
      285,  277,   61,   61,   61,   61,   61,   61,   61,  277,

       61,   61,   61,   61,   61,   61,  280,  271,  271,  271,
      276,  276,  276,  276,  276,  271,  276,  271,  276,  276,
      276,  276,  124,  277,  277,  277,   61,   61,   61,   61,
       61,  277,   61,  277,   61,   61,   61,   61,  276,  276,
      276,  271,  271,  271,   61,   61,   61,  277,  277,  277,
      276,  271,  271,  271,   61,  277,  277,  277,  276,  271,
      271,   61,  277,  277,  271,  271,  277,  277,  271,  277,
        0,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271
    } ;

static const flex_int16_t yy_nxt[1351] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,    6,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   29,   29,
       32,   29,   33,   34,   35,   29,   29,   36,   29,   37,
       29,    6,   38,   29,   26,   27,   28,   29,   30,   31,
       29,   32,   29,   33,   34,   35,   29,   29,   36,   29,
       37,   39,   40,   29,   41,   42,   43,   42,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   41,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   64,   64,   67,   64,   68,   69,   70,   64,

       64,   71,   64,   72,   64,   41,   73,   64,   61,   62,
       63,   64,   65,   66,   64,   67,   64,   68,   69,   70,
       64,   64,   71,   64,   72,   74,   75,   64,   76,   76,
       76,   76,   76,   76,   83,   87,   89,   95,   90,  140,
       88,   92,   93,   96,   96,   96,  135,  136,   91,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   78,   98,
      140,  122,   96,   96,   96,   98,   78,   84,   98,   80,
       91,   98,  119,   76,  119,   99,  101,  100,   98,   96,
       96,   96,  271,  106,  271,  165,  165,   97,  225,  271,
       96,   96,   96,   83,  225,   98,   99,   82,  101,  100,

       96,   96,   96,  107,  108,  106,   98,  109,  110,  102,
      102,  102,  102,  209,  167,  103,   98,   96,   96,   96,
       76,   76,   76,  111,  107,  108,   84,  112,  109,  110,
      209,  104,  105,   98,   96,   96,   96,   82,   96,   96,
       96,  165,  165,  126,  111,   82,  190,  132,  112,  133,
       98,  113,  104,  105,   98,  184,  143,  167,  162,  134,
      144,  190,  114,  140,  153,  140,  116,  140,  115,  165,
      188,  140,  113,   76,   76,   76,  127,  164,  143,  163,
      162,  134,  144,  114,  140,  153,  140,  116,  140,  115,
      118,  118,  140,  118,  118,  118,  118,  118,  118,  118,

      192,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      124,  118,  118,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  118,  118,  123,  118,  118,  130,  118,  118,  118,
      118,  118,  118,  118,  125,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  118,  118,  138,  138,  138,

      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  118,  118,  138,  118,  139,
       96,  139,  118,  118,  118,  118,  118,  118,  121,  118,
      118,  118,  118,  118,  140,  141,  118,  118,  118,  118,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  142,  140,  140,  140,  140,  140,  140,  140,  118,
      118,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  142,  140,  140,  140,  140,  140,  140,  118,
      118,  140,  145,  149,  145,  150,  151,  146,  159,  152,
      140,  154,  140,  157,  140,  155,  140,  140,  156,  158,

      119,   76,  119,  147,  148,  149,  150,  151,  140,  159,
      152,  140,  154,  140,  157,  140,  155,  140,  140,  156,
      158,   86,  165,  188,  147,  148,   89,  167,   90,  140,
      164,  166,   96,   96,   96,   96,   96,   96,   91,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   98,   78,
      169,   98,  122,  166,  145,   98,  145,   78,   98,  190,
       91,   98,  146,  170,   86,  162,   96,   96,   96,  271,
       96,   96,   96,   96,   96,   96,   82,   78,  171,  140,
      172,  103,   98,   79,  160,  170,   98,  162,  130,   98,
       96,   96,   96,   96,   96,   96,  140,  174,  189,  171,

      140,  172,   96,   96,   96,  173,   98,  198,  140,   98,
      137,  177,  177,  177,   96,   96,   96,  140,   98,  174,
      189,  175,  176,   96,   96,   96,  173,   98,  198,  140,
       98,   96,   96,   96,   96,   96,   96,  207,  131,   98,
       82,  130,  175,  176,  178,  129,  126,   98,   82,  128,
       98,   96,   96,   96,   96,   96,   96,  120,  207,  179,
      140,  117,  180,  195,   94,  178,  132,   98,  133,   86,
       98,   96,   96,   96,   85,  266,  181,  193,  134,  127,
      179,  140,  140,  180,  195,  140,  194,   98,  139,   96,
      139,  182,  140,  203,  140,  196,  183,  266,  181,  193,

      134,   81,   79,  140,  141,   77,  140,  194,  210,  210,
      210,  271,  182,  140,  203,  140,  196,  271,  183,  118,
      118,  197,  118,  118,  118,  118,  118,  118,  118,  140,
      118,  118,  118,  118,  118,  204,  118,  118,  118,  118,
      118,  199,  140,  197,  140,  200,  177,  200,  140,  201,
      140,  140,  202,  140,  208,  140,  208,  204,  205,  209,
      118,  118,  199,  140,  271,  140,  224,  271,  224,  140,
      201,  225,  140,  202,  140,  271,  140,  140,  271,  205,
      118,  118,  118,  118,  271,  118,  118,  118,  118,  118,
      118,  118,  271,  118,  118,  118,  118,  118,  140,  118,

      118,  118,  118,  118,  185,  206,   96,   96,   96,  184,
      271,  271,  140,   96,   96,   96,  218,  218,  218,  226,
      210,  226,   98,  118,  118,  186,  185,  206,  271,   98,
      184,  184,   98,  140,  210,  210,  210,  271,  271,   96,
       96,   96,  271,  118,  118,  118,  118,  271,  118,  118,
      118,  118,  118,  118,  118,   98,  118,  118,  118,  118,
      118,  140,  118,  118,  118,  118,  118,   96,   96,   96,
      271,  268,   96,   96,   96,  271,  271,  211,   96,   96,
       96,  271,  140,   98,  271,  271,  118,  118,   98,  177,
      177,  177,  212,  268,   98,  235,  140,  213,  211,   96,

       96,   96,   96,   96,   96,   98,  118,  118,   96,   96,
       96,  271,  271,  214,  212,   98,  235,  140,   98,  213,
      140,  216,  271,  271,   98,  271,  227,  217,  271,  215,
       96,   96,   96,  184,  214,   96,   96,   96,  271,  219,
      236,  140,  216,   96,   96,   96,   98,  227,  223,  217,
      215,   98,  238,  242,  184,  184,  228,  229,  233,   98,
      219,  236,  220,  140,  140,  140,  140,  222,  221,  223,
      226,  210,  226,  238,  242,  234,  218,  234,  228,  229,
      233,  271,  271,  220,  140,  140,  140,  140,  222,  271,
      221,  118,  118,  140,  118,  118,  118,  118,  118,  118,

      118,  184,  118,  118,  118,  118,  118,  140,  118,  118,
      118,  118,  118,  140,  140,  231,  230,  140,  237,  200,
      177,  200,  184,  184,  271,  140,  271,  271,  140,   96,
       96,   96,  118,  118,  140,  141,  231,  230,  140,  271,
      237,   96,   96,   96,  271,   98,  140,   96,   96,   96,
      248,  232,  118,  118,  239,  271,  271,   98,   96,   96,
       96,  140,  271,   98,   96,   96,   96,  140,   96,   96,
       96,  248,  232,  271,   98,  271,  239,  218,  218,  218,
       98,  271,  140,  240,   98,   96,   96,   96,  140,  241,
      271,  271,  271,   98,   96,   96,   96,   96,   96,   96,

      245,   98,   96,   96,   96,  240,  243,  140,  244,  246,
       98,  241,  247,   98,  140,  140,  140,  140,   98,  140,
      271,  271,  245,  234,  218,  234,  271,  243,  140,  244,
      252,  246,  253,  271,  247,  140,  140,  140,  140,  141,
      140,   96,   96,   96,   96,   96,   96,   96,   96,   96,
      254,  252,  249,  253,  250,  255,  271,   98,  140,  140,
       98,  256,  140,   98,  257,  258,  251,  271,   96,   96,
       96,  254,  260,  249,  261,  250,  262,  255,  263,  140,
      140,  264,  256,  140,   98,  257,  258,  265,  251,   96,
       96,   96,  140,  260,  267,  261,  269,  262,  270,  263,

      259,  271,  264,  271,  271,   98,  271,  271,  265,  271,
      271,  271,  271,  140,  271,  267,  271,  271,  269,  271,
      270,  259,   78,   78,   78,   78,   78,   78,   82,   82,
       82,   82,   82,   82,   97,   97,  271,   97,   97,  118,
      118,  271,  271,  118,  118,  121,  121,  121,  121,  121,
      121,  125,  125,  125,  125,  125,  125,  161,  161,  164,
      164,  164,  164,  164,  164,  168,  168,  184,  184,  271,
      271,  184,  184,  187,  187,  187,  187,  187,  187,  191,
      191,  271,  271,  191,  191,    5,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271
    } ;

static const flex_int16_t yy_chk[1351] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    7,    7,
        7,    8,    8,    8,   13,   20,   21,  275,   21,   64,
       20,   22,   22,   26,   26,   26,   57,   57,   21,   29,
       29,   29,   27,   27,   27,   28,   28,   28,   45,   26,
       64,   45,   31,   31,   31,   29,   45,   13,   27,  273,
       21,   28,   42,   42,   42,   26,   28,   27,   31,   33,
       33,   33,   32,   31,   32,   85,   85,   32,  225,  127,
       34,   34,   34,   82,  224,   33,   26,  127,   28,   27,

       30,   30,   30,   32,   32,   31,   34,   32,   33,   91,
       30,   91,   30,  209,   91,   30,   30,   35,   35,   35,
       43,   43,   43,   34,   32,   32,   82,   34,   32,   33,
      208,   30,   30,   35,   36,   36,   36,   48,   37,   37,
       37,  164,  164,   48,   34,   48,  190,   56,   34,   56,
       36,   35,   30,   30,   37,  186,   62,  167,   81,   56,
       63,  145,   36,   62,   68,  140,   37,   68,   36,  129,
      129,   63,   35,   76,   76,   76,   48,  129,   62,   81,
       81,   56,   63,   36,   62,   68,  140,   37,   68,   36,
       46,   46,   63,   46,   46,   46,   46,   46,   46,   46,

      141,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   60,   60,  132,   60,   60,   60,
       60,   60,   60,   60,  126,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,  122,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   65,   66,   65,   67,   67,   65,   72,   67,
       69,   69,   72,   71,   66,   69,   70,   71,   70,   71,

      119,  119,  119,   65,   65,   66,   67,   67,  151,   72,
       67,   69,   69,   72,   71,   66,   69,   70,   71,   70,
       71,   86,  187,  187,   65,   65,   90,  102,   90,  151,
      187,   86,   96,   96,   96,   97,   97,   97,   90,   99,
       99,   99,  100,  100,  100,  101,  101,  101,   96,  121,
       98,   97,  121,   86,  134,   99,  134,  121,  100,  134,
       90,  101,  146,   99,   89,  163,  103,  103,  103,   84,
      104,  104,  104,  105,  105,  105,   83,   79,  100,  146,
      101,  103,  103,   78,   74,   99,  104,  163,  130,  105,
      106,  106,  106,  107,  107,  107,  156,  105,  130,  100,

      146,  101,  108,  108,  108,  104,  106,  149,  149,  107,
       59,  109,  109,  109,  110,  110,  110,  156,  108,  105,
      130,  106,  107,  111,  111,  111,  104,  109,  149,  149,
      110,  112,  112,  112,  113,  113,  113,  162,   55,  111,
      125,   54,  106,  107,  110,   53,  125,  112,  125,   50,
      113,  114,  114,  114,  115,  115,  115,   44,  162,  111,
      144,   39,  112,  144,   24,  110,  133,  114,  133,   19,
      115,  116,  116,  116,   18,  261,  114,  142,  133,  125,
      111,  144,  143,  112,  144,  142,  143,  116,  139,  139,
      139,  115,  147,  155,  155,  147,  116,  261,  114,  142,

      133,   11,   10,  143,  139,    9,  142,  143,  169,  169,
      169,    5,  115,  147,  155,  155,  147,    0,  116,  123,
      123,  148,  123,  123,  123,  123,  123,  123,  123,  148,
      123,  123,  123,  123,  123,  157,  123,  123,  123,  123,
      123,  150,  157,  148,  150,  152,  152,  152,  154,  153,
      148,  153,  154,  158,  166,  193,  166,  157,  158,  166,
      123,  123,  150,  157,    0,  150,  189,    0,  189,  154,
      153,  189,  153,  154,  158,    0,  193,  152,    0,  158,
      123,  123,  124,  124,    0,  124,  124,  124,  124,  124,
      124,  124,    0,  124,  124,  124,  124,  124,  152,  124,

      124,  124,  124,  124,  124,  159,  170,  170,  170,  184,
        0,    0,  159,  174,  174,  174,  179,  179,  179,  192,
      192,  192,  170,  124,  124,  124,  124,  159,    0,  174,
      184,  184,  179,  159,  210,  210,  210,    0,    0,  171,
      171,  171,    0,  124,  124,  138,  138,    0,  138,  138,
      138,  138,  138,  138,  138,  171,  138,  138,  138,  138,
      138,  197,  138,  138,  138,  138,  138,  172,  172,  172,
        0,  264,  173,  173,  173,    0,    0,  171,  175,  175,
      175,    0,  197,  172,    0,    0,  138,  138,  173,  177,
      177,  177,  172,  264,  175,  203,  203,  173,  171,  176,

      176,  176,  178,  178,  178,  177,  138,  138,  180,  180,
      180,    0,    0,  175,  172,  176,  203,  203,  178,  173,
      194,  177,    0,    0,  180,    0,  194,  178,    0,  176,
      181,  181,  181,  185,  175,  183,  183,  183,    0,  180,
      204,  194,  177,  182,  182,  182,  181,  194,  185,  178,
      176,  183,  206,  216,  185,  185,  195,  196,  201,  182,
      180,  204,  181,  195,  196,  201,  228,  183,  182,  185,
      226,  226,  226,  206,  216,  202,  202,  202,  195,  196,
      201,    0,    0,  181,  195,  196,  201,  228,  183,    0,
      182,  191,  191,  229,  191,  191,  191,  191,  191,  191,

      191,  223,  191,  191,  191,  191,  191,  202,  191,  191,
      191,  191,  191,  198,  229,  199,  198,  199,  205,  200,
      200,  200,  223,  223,    0,  205,    0,    0,  202,  211,
      211,  211,  191,  191,  198,  200,  199,  198,  199,    0,
      205,  212,  212,  212,    0,  211,  205,  213,  213,  213,
      232,  200,  191,  191,  211,    0,    0,  212,  214,  214,
      214,  233,    0,  213,  215,  215,  215,  235,  217,  217,
      217,  232,  200,    0,  214,    0,  211,  218,  218,  218,
      215,    0,  233,  214,  217,  219,  219,  219,  235,  215,
        0,    0,    0,  218,  220,  220,  220,  221,  221,  221,

      227,  219,  222,  222,  222,  214,  218,  227,  218,  230,
      220,  215,  231,  221,  236,  237,  230,  238,  222,  231,
        0,    0,  227,  234,  234,  234,    0,  218,  227,  218,
      242,  230,  243,    0,  231,  236,  237,  230,  238,  234,
      231,  239,  239,  239,  240,  240,  240,  241,  241,  241,
      244,  242,  234,  243,  234,  245,    0,  239,  246,  247,
      240,  248,  245,  241,  249,  250,  239,    0,  251,  251,
      251,  244,  253,  234,  254,  234,  255,  245,  257,  246,
      247,  258,  248,  245,  251,  249,  250,  260,  239,  259,
      259,  259,  262,  253,  263,  254,  265,  255,  267,  257,

      251,    0,  258,    0,    0,  259,    0,    0,  260,    0,
        0,    0,    0,  262,    0,  263,    0,    0,  265,    0,
      267,  251,  272,  272,  272,  272,  272,  272,  274,  274,
      274,  274,  274,  274,  276,  276,    0,  276,  276,  277,
      277,    0,    0,  277,  277,  278,  278,  278,  278,  278,
      278,  279,  279,  279,  279,  279,  279,  280,  280,  281,
      281,  281,  281,  281,  281,  282,  282,  283,  283,    0,
        0,  283,  283,  284,  284,  284,  284,  284,  284,  285,
      285,    0,    0,  285,  285,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[55] =
    {   0,
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "src/core/qgsexpressionlexer.ll"
/***************************************************************************
                          qgsexpressionlexer.ll
                          --------------------
    begin                : August 2011
    copyright            : (C) 2011 by Martin Dobias
    email                : wonder.sk at gmail dot com
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
#line 22 "src/core/qgsexpressionlexer.ll"
 // this makes flex generate lexer with context + init/destroy functions
 // this makes Bison send yylex another argument to use instead of using the global variable yylval
 // ensure that lexer will be 8-bit (and not just 7-bit)

#include <stdlib.h>  // atof()

#include "qgsexpression.h"
#include "expression/qgsexpressionnodeimpl.h"
#include "qgsexpressionfunction.h"
        struct expression_parser_context;
#include "qgsexpressionparser.hpp"
#include <QLocale>

// if not defined, searches for isatty()
// which doesn't in MSVC compiler
#define YY_NEVER_INTERACTIVE 1

#ifndef YY_NO_UNPUT
#define YY_NO_UNPUT	// unused
#endif

#ifdef _MSC_VER
#define YY_NO_UNISTD_H
#endif

#define B_OP(x) yylval->b_op = QgsExpressionNodeBinaryOperator::x
#define U_OP(x) yylval->u_op = QgsExpressionNodeUnaryOperator::x
#define TEXT                   yylval->text = new QString( QString::fromUtf8(yytext) );
#define TEXT_FILTER(filter_fn) yylval->text = new QString( filter_fn( QString::fromUtf8(yytext) ) );

#define YY_USER_ACTION \
    yylloc->first_line = yylloc->last_line; \
    yylloc->first_column = yylloc->last_column; \
    for(int i = 0; yytext[i] != '\0'; i++) { \
    if(yytext[i] == '\n') { \
        yylloc->last_line++; \
        yylloc->last_column = 0; \
    } \
    else { \
        yylloc->last_column++; \
    } \
}

static QString stripText(QString text)
{
  // strip single quotes on start,end
  text = text.mid( 1, text.length() - 2 );

  // make single "single quotes" from double "single quotes"
  text.replace( "''", "'" );

  // strip \n \' etc.
  int index = 0;
  while (( index = text.indexOf( '\\', index ) ) != -1 )
  {
    text.remove( index, 1 ); // delete backslash
    QChar chr;
    switch ( text[index].toLatin1() ) // evaluate backslashed character
    {
      case 'n':  chr = '\n'; break;
      case 't':  chr = '\t'; break;
      case '\\': chr = '\\'; break;
      case '\'': chr = '\''; break;
      default: chr = '?'; break;
    }
    text[index++] = chr; // set new character and push index +1
  }
  return text;
}

static QString stripNamedText(QString text)
{
  text.remove(":=");
  return text.trimmed();
}

static QString stripColumnRef(QString text)
{
  // strip double quotes on start,end
  text = text.mid( 1, text.length() - 2 );

  // make single "double quotes" from double "double quotes"
  text.replace( "\"\"", "\"" );
  return text;
}

// C locale for correct parsing of numbers even if the system locale is different
Q_GLOBAL_STATIC_WITH_ARGS(QLocale, cLocale, ("C") )

#line 1174 "src/core/flex_qgsexpressionlexer.cpp"

#line 1176 "src/core/flex_qgsexpressionlexer.cpp"

#define INITIAL 0
#define BLOCK_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 150 "src/core/qgsexpressionlexer.ll"


#line 1462 "src/core/flex_qgsexpressionlexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 272 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 271 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 153 "src/core/qgsexpressionlexer.ll"
BEGIN(BLOCK_COMMENT);
	YY_BREAK


case 2:
YY_RULE_SETUP
#line 156 "src/core/qgsexpressionlexer.ll"
BEGIN(INITIAL);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 157 "src/core/qgsexpressionlexer.ll"
// eat comment in chunks
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 158 "src/core/qgsexpressionlexer.ll"
// eat the lone star
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 159 "src/core/qgsexpressionlexer.ll"
yylineno++;
	YY_BREAK

case 6:
YY_RULE_SETUP
#line 162 "src/core/qgsexpressionlexer.ll"
{ U_OP(uoNot); return NOT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 163 "src/core/qgsexpressionlexer.ll"
{ B_OP(boAnd); return AND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 164 "src/core/qgsexpressionlexer.ll"
{ B_OP(boOr);  return OR;  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 166 "src/core/qgsexpressionlexer.ll"
{ B_OP(boEQ); return EQ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 167 "src/core/qgsexpressionlexer.ll"
{ B_OP(boNE); return NE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 168 "src/core/qgsexpressionlexer.ll"
{ B_OP(boLE); return LE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 169 "src/core/qgsexpressionlexer.ll"
{ B_OP(boGE); return GE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 170 "src/core/qgsexpressionlexer.ll"
{ B_OP(boNE); return NE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 171 "src/core/qgsexpressionlexer.ll"
{ B_OP(boLT); return LT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 172 "src/core/qgsexpressionlexer.ll"
{ B_OP(boGT); return GT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 174 "src/core/qgsexpressionlexer.ll"
{ B_OP(boRegexp); return REGEXP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 175 "src/core/qgsexpressionlexer.ll"
{ B_OP(boLike); return LIKE; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 176 "src/core/qgsexpressionlexer.ll"
{ B_OP(boNotLike); return LIKE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 177 "src/core/qgsexpressionlexer.ll"
{ B_OP(boILike); return LIKE; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 178 "src/core/qgsexpressionlexer.ll"
{ B_OP(boNotILike); return LIKE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 179 "src/core/qgsexpressionlexer.ll"
{ B_OP(boIs); return IS; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 180 "src/core/qgsexpressionlexer.ll"
{ B_OP(boIsNot); return IS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 181 "src/core/qgsexpressionlexer.ll"
{ B_OP(boConcat); return CONCAT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 183 "src/core/qgsexpressionlexer.ll"
{ B_OP(boPlus); return PLUS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 184 "src/core/qgsexpressionlexer.ll"
{ B_OP(boMinus); return MINUS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 185 "src/core/qgsexpressionlexer.ll"
{ B_OP(boMul); return MUL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 186 "src/core/qgsexpressionlexer.ll"
{ B_OP(boIntDiv); return INTDIV; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 187 "src/core/qgsexpressionlexer.ll"
{ B_OP(boDiv); return DIV; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 188 "src/core/qgsexpressionlexer.ll"
{ B_OP(boMod); return MOD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 189 "src/core/qgsexpressionlexer.ll"
{ B_OP(boPow); return POW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 191 "src/core/qgsexpressionlexer.ll"
{ return IN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 192 "src/core/qgsexpressionlexer.ll"
{ return BETWEEN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 194 "src/core/qgsexpressionlexer.ll"
{ return NULLVALUE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 196 "src/core/qgsexpressionlexer.ll"
{ return CASE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 197 "src/core/qgsexpressionlexer.ll"
{ return WHEN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 198 "src/core/qgsexpressionlexer.ll"
{ return THEN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 199 "src/core/qgsexpressionlexer.ll"
{ return ELSE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 200 "src/core/qgsexpressionlexer.ll"
{ return END;  }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 202 "src/core/qgsexpressionlexer.ll"
{ return yytext[0]; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 204 "src/core/qgsexpressionlexer.ll"
{ return COMMA; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 206 "src/core/qgsexpressionlexer.ll"
{ yylval->numberFloat = cLocale()->toDouble( QString::fromLatin1(yytext) ); return NUMBER_FLOAT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 207 "src/core/qgsexpressionlexer.ll"
{
	bool ok;
	yylval->numberInt = cLocale()->toInt( QString::fromLatin1(yytext), &ok );
	if( ok )
		return NUMBER_INT;

  yylval->numberInt64 = cLocale()->toLongLong( QString::fromLatin1(yytext), &ok );
  if( ok )
    return NUMBER_INT64;

	yylval->numberFloat = cLocale()->toDouble( QString::fromLatin1(yytext), &ok );
	if( ok )
		return NUMBER_FLOAT;

	return Unknown_CHARACTER;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 224 "src/core/qgsexpressionlexer.ll"
{ yylval->boolVal = QString( yytext ).compare( "true", Qt::CaseInsensitive ) == 0; return BOOLEAN; }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 226 "src/core/qgsexpressionlexer.ll"
{ TEXT_FILTER(stripText); return STRING; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 228 "src/core/qgsexpressionlexer.ll"
{ TEXT; return NAME; }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 230 "src/core/qgsexpressionlexer.ll"
{ TEXT_FILTER(stripNamedText); return NAMED_NODE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 232 "src/core/qgsexpressionlexer.ll"
{ TEXT; return SPECIAL_COL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 234 "src/core/qgsexpressionlexer.ll"
{ TEXT; return VARIABLE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 236 "src/core/qgsexpressionlexer.ll"
{ TEXT; return NAME; }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 238 "src/core/qgsexpressionlexer.ll"
{ TEXT_FILTER(stripColumnRef); return QUOTED_COLUMN_REF; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 240 "src/core/qgsexpressionlexer.ll"
/* skip blanks and tabs */
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 242 "src/core/qgsexpressionlexer.ll"
/* skip line comments */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 244 "src/core/qgsexpressionlexer.ll"
{ return Unknown_CHARACTER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 247 "src/core/qgsexpressionlexer.ll"
ECHO;
	YY_BREAK
#line 1824 "src/core/flex_qgsexpressionlexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLOCK_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 272 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 272 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 271);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 247 "src/core/qgsexpressionlexer.ll"


